### ISSUE TITLE
allowDuplicates parameter for startScanning() is not implemented

### ISSUE THREAD

**Issue by hoffmannjan** [jasongin/noble-uwp#19]
Hi, as I see in [source code](https://github.com/jasongin/noble-uwp/blob/master/lib/bindings.js#L74-L81) the option about allowDuplicates isn't interpreted in any way.
Is this because of lack of setting this in Windows 10 Bluetooth API (can't find anything about this in documentation) or I should configure this in other place?

I'm using this to detect disconnection of BT device, in noble this way works well but transfer to -uwp causes this kind of problems.

**Comment by jasongin** [comment]
Right, the Windows 10 Bluetooth API doesn't provide any way to ignore duplicate scan results. However, I think this could be implemented in `noble-uwp`, in [the `_onAdvertisementWatcherReceived()` callback](https://github.com/jasongin/noble-uwp/blob/master/lib/bindings.js#L435), by keeping track of what addresses have been scanned so far and using that list to avoid emitting duplicate `"discover"` events.

You're welcome to submit a PR! Otherwise I will try to get to this eventually.

**Comment by jasongin** [comment]
This is implemented now, in version 0.5.0. Can  you confirm that it works how you expect?

**Comment by hoffmannjan** [comment]
Yes, can confirm! Thanks!
