### ISSUE TITLE
"Protocol error communicating with device" while trying to read

### ISSUE THREAD

**Issue by hoffmannjan** [jasongin/noble-uwp#26]
Hi,

I was trying to simple try some another devices according to bug [#24](https://github.com/jasongin/noble-uwp/issues/24), and while using LightBlue Explorer on my iPhone to create Virtual Periperals I got this as a value (sic!) on .read() some of the characteristics

`Protocol error communicating with device` 

Seemed pretty strange for me so I tried same code on macOS & noble and got proper value.

Best, JH

**Comment by jasongin** [comment]
I don't know what might have caused the protocol error. As for why you got the error message back instead of the value... Currently whenever `noble-uwp` encounters an error, it returns the `Error` object as the result. So, you could check if the results is an `instanceof Error` to detect that.

That's probably not the way it should work, though I'm not sure what it should do instead. From what I can see, noble bindings for other platforms don't have consistent error-handling though. Some report errors via `console.error()`, and some just don't catch exceptions (so they would propagate up the stack and kill the process.
